export { CHART_KINDS, validateChartContent } from './schema.js';
export type { ChartContent, ChartSpec, ChartKind, Dimension, Measure } from './schema.js';
export type { SceneNode, Scene, ChartSemanticRole, Bounds } from './scene/types.js';
export { buildScene } from './scene/build.js';
export { layout } from './layout/engine.js';
export type { LayoutContext } from './layout/engine.js';
export { linearScale, bandScale, niceTicks, barDomain, lineDomain } from './layout/scales.js';
export { svgFrom } from './render/svg.js';
export type { SvgResult, TabularRow, A11yNode } from './render/types.js';
export { ChartEngine } from './engine.js';